### ISSUE TITLE
Make build process ARM compatible

### ISSUE THREAD

**Issue by tlwt** [SCRATCh-ITEA3/demonstrator#5]
We just tried to run the image on i.MX6 and got the following error message:

```
standard_init_linux.go:190: exec user process caused "exec format error"
```

This seems to be related to the build process and ARM infrastructure (see https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/67). This needs to be investigated and a plan derived how to make the build process compatible.

**Comment by SoberHellman** [comment]
Just tried out the new "buildx" command by docker: https://github.com/docker/buildx
It is an easy way to create an image for multiple platforms. I don't know how easy it is to integrate it into drone.

**Comment by SoberHellman** [comment]
I looked a little bit further. buildx might not be needed. Docker build now supports the --platform "linux/arm/v7" command. This requires that you system is able to build for linux arm. 
I have no experience with drone. But the following docker build command works:
`DOCKER_BUILDKIT=1 docker build --platform "linux/arm/v7" -t "tag" .`

**Comment by tlwt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expand build chain to include armv7l for Raspberry Pi](https://trello.com/c/2o9eb6hF/1-expand-build-chain-to-include-armv7l-for-raspberry-pi)

**Comment by tlwt** [comment]
@SoberHellman - could you make this happen? @ctrl-shift-esc can you check on i.MX if it runs?

**Comment by SoberHellman** [comment]
did some research for drone. Maybe its even easier: https://docs.drone.io/pipeline/docker/syntax/platform/

**Comment by tlwt** [comment]
I think that trick is only to select the platform during execution of the DevOps pipeline, but not for the target image.

**Comment by SoberHellman** [comment]
Thats true, but it also defines the target os and architecture: "Use the platform section to configure the target operating system and architecture and routes the pipeline to the appropriate runner. If unspecified, the system defaults to Linux amd64."
